name: Build and Deploy Dynoform API to GitLab Registry

on:
  push:
    branches:
      - main  # Trigger on push to the main branch. Update if your default branch is different.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitLab Container Registry
      - name: Log in to GitLab Registry
        run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login -u "${{ secrets.GITLAB_USERNAME }}" --password-stdin registry.gitlab.com

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.gitlab.com/dyno1785604/dynoforms -f DynoForm.backend/DynoForm.backend .
          docker push registry.gitlab.com/dyno1785604/dynoforms
